### ISSUE TITLE
Please  add support for Aikagi2

### ISSUE THREAD

**Issue by guitarplayer70** [shahrilnet/remote_lua_loader#16]
Would you please ad Aikagi2 cusa19556

Thank you in advance.

cheers

**Comment by Master-s** [comment]
Upload me the savedata file with PS4/xxxxx/SAVEDATA/CUSA19556

> Would you please ad Aikagi2 cusa19556
> 
> Thank you in advance.
> 
> cheers

Upload me the savedata file with PS4/SAVEDATA//xxxxx/CUSA19556

**Comment by guitarplayer70** [comment]
Thanks a lot, will do it when back from work and.
You mean the file that I create with Apollo or should I take it from path on ftp?

**Comment by Master-s** [comment]
> Here´s my savedata to aikagi2.... thanks a lot in advance for supporting it.
> 
> [PS4-SAVEDATA-AIKAGI2-CUSA19556.zip](https://github.com/user-attachments/files/18168784/PS4-SAVEDATA-AIKAGI2-CUSA19556.zip)

savedata was injected
test 
https://easyupload.io/8uwr0u

**Comment by guitarplayer70** [comment]
> > Here´s my savedata to aikagi2.... thanks a lot in advance for supporting it.
> > [PS4-SAVEDATA-AIKAGI2-CUSA19556.zip](https://github.com/user-attachments/files/18168784/PS4-SAVEDATA-AIKAGI2-CUSA19556.zip)
> 
> savedata was injected test https://easyupload.io/8uwr0u

Unfortunately game still crashes with error code ce-34878-0
Don‘t know if it matters that I’ll tested on a ps4 jailbroken console, does it?
Thanks for your effort anyway.

**Comment by n0llptr** [comment]
There's some problem with the game.  
Will check later and fix it.

**Comment by guitarplayer70** [comment]
> There's some problem with the game. Will check later and fix it.

Do you think it is fixable or do I have to try to find a different Artemis game that already works?

**Comment by Master-s** [comment]
> 
> Unfortunately game still crashes with error code ce-34878-0 Don‘t know if it matters that I’ll tested on a ps4 jailbroken console, does it? Thanks for your effort anyway. Edit: Didn’t connect to internet when running the game, maybe that’s the issue. Will try it again when home from work.👍
> 
> edit2: Had changed the inject.lua file from ps5 to ps4 (since I Test it on ps4) but still the same error…ce-34878-0🤷‍♂️



https://github.com/user-attachments/assets/0b9462df-1bd4-4d8f-8e5c-259f35731c79

It is working fine

decrypted - savedata0
-----------------------------
Method of transfer to USB
encrypted - SAVEDATA

USB = PS4/SAVEDATA/xxxxx/CUSA19556
Download
https://easyupload.io/pwt2kj
